### ISSUE TITLE
수정사항 24.11.22

### ISSUE THREAD

**Issue by YoonjeongYoo** [CoBook-2/CoBook-FE#10]
- [x] getLayout 생성(좌측 참여 스페이스 목록 & 상단 헤더 네이게이션바 레이아웃)
- [x] 글꼴 적용 (Pretendard, GmarketSans)
- [x] HeaderNavbarLayout.module.css 수정
- [x] JoinSpaceLayout.module.css 수정

**Comment by WholeLottaYong** [comment]
윤정아 사이드바쪽(Join~.tsx) 거기 로직 좀 바꿨으니 참고하시오
